BEGIN;
DELETE FROM cespite_storico;
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('computer',48,'2018-06-01','effesistemi srl','computer dei cas PASSATO A SCIDURLO',0.0,0.0,468.95,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('mac',28,'2017-10-19',NULL,'macbook miriam',0.0,0.0,1277.05,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('tablet',49,'2018-02-23','dell sa','ipad andrea',0.0,0.0,508.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',8,'2010-09-28','ieo informatica','server e monitor per amm',NULL,0.0,1042.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',9,'2010-12-09','essedi shop italia srl','mac paladini',NULL,814.22,0.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',10,'2011-01-10','dell sa','computer uff stampa',NULL,274.0,0.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',13,'2011-06-17','amazon eu srl','NOTEBOOK',NULL,362.98,0.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',14,'2011-09-14','essedi shop italia srl','acq mac apple settore grafici',NULL,1062.98,0.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',16,'2011-09-29','ieo informatica','2 pc portatili',NULL,720.0,0.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',17,'2012-01-28','dell sa',NULL,NULL,479.0,0.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',20,'2013-01-24','c.e. communications engineering','acq-mac grafici',NULL,536.36,0.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',22,'2014-06-30','effesistemi srl','pc portatile',0.0,0.0,690.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',24,'2016-11-21','applekingshop','mac mini grafici',NULL,0.0,731.65,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',25,'2016-02-29','diamante srl','pc per pavan',NULL,0.0,1278.13,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',26,'2016-01-29','ieo informatica','pc magri cortese',NULL,0.0,1366.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',44,'2015-01-21','c.e. communications engineering','n.3 apple settori libri',0.0,0.0,1357.38,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',45,'2016-08-29','amazon eu sarl','pc portatile pedretti',0.0,0.0,327.05,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',46,'2017-05-08','dilc srl','pc nuovo amm.ne simona',0.0,0.0,245.08,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',47,'2017-08-30','amazon eu sarl','mac pedretti',0.0,411.2,0.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',50,'2018-08-20','amazon eu sarl','kit memoria',NULL,418.02,0.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',51,'2017-12-14','amazon eu sarl','pc elena acerbi',0.0,0.0,255.57,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',52,'2018-07-04','dell sa','pc cuzzola francesco',0.0,0.0,329.0,NULL);
INSERT INTO cespite_storico (categoria,numero,data,fornitore,descrizione,col_h,da_trovare_eliminare,da_abbinare,note) VALUES ('eliminati',53,'2018-08-28','amazon eu sarl','pc bp 15 bs536nl',0.0,0.0,495.89,NULL);
COMMIT;
