BEGIN;
SET CONSTRAINTS ALL DEFERRED;
-- persone
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (1,'Alberto','Dragone',NULL,NULL,NULL,'Attivo',NULL,NULL,'Email da compilare (sincronizza da Google Workspace)');
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (2,'Alessia','Boccardo','alessiaboccardo@falacosagiusta.org',NULL,NULL,'Cessato','2024-10-15',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (3,'Andrea','Raspanti','andrearaspanti@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (4,'Antonella','Carnicelli','antonellacarnicelli@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (5,'Carola','Fumagalli','carolafumagalli@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (6,'Caterina','Calza','caterinacalza@stage.terre.it',1,NULL,'Attivo','2026-08-25',NULL,'Aggiunto da Workspace il 08/09/2026');
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (7,'Chiara','Cuzzola','chiaracuzzola@falacosagiusta.org',1,NULL,'Attivo','2018-06-01',NULL,'Aggiunto da Workspace il 08/09/2026');
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (8,'Chiara','Righi','chiararighi@falacosagiusta.org',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (9,'Chiara','Seminari','chiaraseminari@terre.it',1,NULL,'Attivo','2023-06-16',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (10,'Corinne','Barbieri','corinnebarbieri@falacosagiusta.org',2,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (11,'Dario','Paladini','dariopaladini@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (12,'Davide','Ioppi','davideioppi@terre.it',1,NULL,'Attivo','2025-06-03',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (13,'Davide','Musso','davidemusso@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (14,'Elena','Acerbi','elenaacerbi@terre.it',2,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (15,'Elena','Mancianti','elenamancianti@terre.it',2,NULL,'Attivo','2024-02-14',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (16,'Elena','Parasiliti','elenaparasiliti@terre.it',1,NULL,'Attivo','2018-09-28',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (17,'Eleonora','Armaroli','eleonoraarmaroli@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (18,'Elisa','Pedretti','elisapedretti@falacosagiusta.org',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (19,'Erika','Scafuro','erikascafuro@collaboratori.terre.it',1,NULL,'Cessato','2023-04-17',NULL,'Aggiunto da Workspace il 08/09/2026');
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (20,'Fausto','Trucillo','faustotrucillo@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (21,'Francesca','Clarichetti','francescaclarichetti@falacosagiusta.org',1,NULL,'Attivo','2019-01-07',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (22,'Francesca','Vita','francescavita@terre.it',1,NULL,'Attivo','2025-09-17',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (23,'Francesco','Cuzzola','francescocuzzola@falacosagiusta.org',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (24,'Giovannella','Dall''Ara','giovannelladallara@falacosagiusta.org',1,NULL,'Attivo','2023-09-01',NULL,'Aggiunto da Workspace il 08/09/2026');
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (25,'Giulia','Genovesi','giuliagenovesi@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (26,'Giulia','Rizzo','giuliarizzo@terre.it',1,NULL,'Attivo','2022-12-28',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (27,'Giuseppe','Favi','giuseppefavi@terre.it',1,NULL,'Attivo','2024-07-18',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (28,'Guido','Panduro','guidopanduro@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (29,'Isabella','Pavan','isabellapavan@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (30,'Lapo','Moscon','video@terre.it',1,NULL,'Attivo','2025-09-15',NULL,'Aggiunto da Workspace il 08/09/2026');
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (31,'Lorena','Colnaghi','lorenacolnaghi@leparolecheservono.it',2,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (32,'Luca','Dei Cas','lucadeicas@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (33,'Lucia','Chierici','luciachierici@terre.it',1,NULL,'Attivo','2022-08-31',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (34,'Ludovica','Marcacci Balestrazzi','ludovicamarcaccibalestrazzi@terre.it',1,NULL,'Attivo','2021-09-14',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (35,'Maria','Santagata',NULL,1,NULL,'Attivo',NULL,NULL,'Email da compilare (sincronizza da Google Workspace)');
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (36,'Martina','Malachin','martinamalachin@falacosagiusta.org',2,NULL,'Attivo','2020-10-02',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (37,'Mattia','Gadda',NULL,1,NULL,'Cessato',NULL,NULL,'Email da compilare (sincronizza da Google Workspace)');
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (38,'Miriam','Giovanzana','miriamgiovanzana@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (39,'Piero','Magri','pieromagri@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (40,'Pietro','Scidurlo','pietroscidurlo@terre.it',1,NULL,'Attivo','2021-09-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (41,'Rossella','Cortese','rossellacortese@falacosagiusta.org',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (42,'Sabina','Eleonori','sabinaeleonori@leparolecheservono.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (43,'Sara','Pizzardo','sarapizzardo@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (44,'Sara','Ragusa','sararagusa@terre.it',1,NULL,'Attivo','2018-06-01',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (45,'Stefania','Falbo','stefaniafalbo@terre.it',1,NULL,'Attivo','2018-07-17',NULL,NULL);
INSERT INTO persona (id,nome,cognome,email,azienda_id,reparto,stato,data_ingresso,data_uscita,note) VALUES (46,'Viola','Cappelluti','violacappelluti@stage.terre.it',1,NULL,'Cessato','2025-08-25',NULL,NULL);
-- fornitori, cespiti, fatture
INSERT INTO fornitore (id,nome) VALUES (1,'Effesistemi');
INSERT INTO fornitore (id,nome) VALUES (2,'Groove to');
INSERT INTO fornitore (id,nome) VALUES (3,'Amazon');
INSERT INTO fornitore (id,nome) VALUES (4,'Realtechnology');
INSERT INTO fornitore (id,nome) VALUES (5,'Tre esse');
INSERT INTO fornitore (id,nome) VALUES (6,'Cart''armata edizioni');
INSERT INTO fornitore (id,nome) VALUES (7,'MediaWorld');
INSERT INTO fornitore (id,nome) VALUES (8,'Arce byte');
INSERT INTO fornitore (id,nome) VALUES (9,'Ceo informatica');
INSERT INTO fornitore (id,nome) VALUES (10,'Otomac');
INSERT INTO fornitore (id,nome) VALUES (11,'Juice');
INSERT INTO fornitore (id,nome) VALUES (12,'Wind Tre');
INSERT INTO fornitore (id,nome) VALUES (13,'Unieuro');
INSERT INTO fornitore (id,nome) VALUES (14,'Infodigita');
INSERT INTO fornitore (id,nome) VALUES (15,'Setis');
INSERT INTO fornitore (id,nome) VALUES (16,'Multimedia');
INSERT INTO cespite (id,azienda_id,numero) VALUES (1,1,48);
INSERT INTO cespite (id,azienda_id,numero) VALUES (2,1,57);
INSERT INTO cespite (id,azienda_id,numero) VALUES (3,1,68);
INSERT INTO cespite (id,azienda_id,numero) VALUES (4,1,80);
INSERT INTO cespite (id,azienda_id,numero) VALUES (5,1,83);
INSERT INTO cespite (id,azienda_id,numero) VALUES (6,1,84);
INSERT INTO cespite (id,azienda_id,numero) VALUES (7,1,89);
INSERT INTO cespite (id,azienda_id,numero) VALUES (8,1,94);
INSERT INTO cespite (id,azienda_id,numero) VALUES (9,1,95);
INSERT INTO cespite (id,azienda_id,numero) VALUES (10,1,96);
INSERT INTO cespite (id,azienda_id,numero) VALUES (11,1,97);
INSERT INTO cespite (id,azienda_id,numero) VALUES (12,1,98);
INSERT INTO cespite (id,azienda_id,numero) VALUES (13,1,107);
INSERT INTO cespite (id,azienda_id,numero) VALUES (14,1,109);
INSERT INTO cespite (id,azienda_id,numero) VALUES (15,1,115);
INSERT INTO cespite (id,azienda_id,numero) VALUES (16,1,114);
INSERT INTO cespite (id,azienda_id,numero) VALUES (17,1,116);
INSERT INTO cespite (id,azienda_id,numero) VALUES (18,1,117);
INSERT INTO cespite (id,azienda_id,numero) VALUES (19,1,118);
INSERT INTO cespite (id,azienda_id,numero) VALUES (20,1,120);
INSERT INTO cespite (id,azienda_id,numero) VALUES (21,1,60);
INSERT INTO cespite (id,azienda_id,numero) VALUES (22,1,112);
INSERT INTO cespite (id,azienda_id,numero) VALUES (23,2,5);
INSERT INTO cespite (id,azienda_id,numero) VALUES (24,2,12);
INSERT INTO cespite (id,azienda_id,numero) VALUES (25,2,28);
INSERT INTO cespite (id,azienda_id,numero) VALUES (26,2,29);
INSERT INTO cespite (id,azienda_id,numero) VALUES (27,1,131);
INSERT INTO cespite (id,azienda_id,numero) VALUES (28,1,49);
INSERT INTO cespite (id,azienda_id,numero) VALUES (29,1,69);
INSERT INTO cespite (id,azienda_id,numero) VALUES (30,1,81);
INSERT INTO cespite (id,azienda_id,numero) VALUES (31,1,28);
INSERT INTO cespite (id,azienda_id,numero) VALUES (32,1,105);
INSERT INTO cespite (id,azienda_id,numero) VALUES (33,1,70);
INSERT INTO cespite (id,azienda_id,numero) VALUES (34,1,85);
INSERT INTO cespite (id,azienda_id,numero) VALUES (35,1,79);
INSERT INTO cespite (id,azienda_id,numero) VALUES (36,1,82);
INSERT INTO cespite (id,azienda_id,numero) VALUES (37,1,88);
INSERT INTO cespite (id,azienda_id,numero) VALUES (38,1,87);
INSERT INTO cespite (id,azienda_id,numero) VALUES (39,1,90);
INSERT INTO cespite (id,azienda_id,numero) VALUES (40,1,93);
INSERT INTO cespite (id,azienda_id,numero) VALUES (41,1,106);
INSERT INTO cespite (id,azienda_id,numero) VALUES (42,1,108);
INSERT INTO cespite (id,azienda_id,numero) VALUES (43,1,58);
INSERT INTO cespite (id,azienda_id,numero) VALUES (44,1,113);
INSERT INTO cespite (id,azienda_id,numero) VALUES (45,1,119);
INSERT INTO cespite (id,azienda_id,numero) VALUES (46,1,92);
INSERT INTO cespite (id,azienda_id,numero) VALUES (47,1,122);
INSERT INTO cespite (id,azienda_id,numero) VALUES (48,1,91);
INSERT INTO cespite (id,azienda_id,numero) VALUES (49,1,123);
INSERT INTO cespite (id,azienda_id,numero) VALUES (50,1,124);
INSERT INTO cespite (id,azienda_id,numero) VALUES (51,2,3);
INSERT INTO cespite (id,azienda_id,numero) VALUES (52,2,38);
INSERT INTO cespite (id,azienda_id,numero) VALUES (53,2,22);
INSERT INTO cespite (id,azienda_id,numero) VALUES (54,2,21);
INSERT INTO cespite (id,azienda_id,numero) VALUES (55,1,111);
INSERT INTO cespite (id,azienda_id,numero) VALUES (56,1,29);
INSERT INTO cespite (id,azienda_id,numero) VALUES (57,1,27);
INSERT INTO cespite (id,azienda_id,numero) VALUES (58,1,59);
INSERT INTO cespite (id,azienda_id,numero) VALUES (59,1,135);
INSERT INTO cespite (id,azienda_id,numero) VALUES (60,1,132);
INSERT INTO cespite (id,azienda_id,numero) VALUES (61,1,133);
INSERT INTO cespite (id,azienda_id,numero) VALUES (62,2,6);
INSERT INTO cespite (id,azienda_id,numero) VALUES (63,2,16);
INSERT INTO cespite (id,azienda_id,numero) VALUES (64,1,136);
INSERT INTO cespite (id,azienda_id,numero) VALUES (65,1,134);
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (1,1,'4198.0','2018-06-01');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (2,1,'748/l','2018-10-31');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (3,1,'476.0','2019-10-04');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (4,1,'480/r','2020-10-29');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (5,1,'213.0','2021-04-27');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (6,1,'242.0','2021-05-13');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (7,2,'8553.0','2022-11-24');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (8,3,'5767588.0','2023-05-16');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (9,1,'255.0','2023-08-31');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (10,1,'262.0','2023-09-07');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (11,1,'277.0','2023-09-19');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (12,4,'3988/I','2023-09-23');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (13,3,'999/A','2024-06-03');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (14,3,'IT24-75991I-3488','2024-08-13');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (15,1,'123.0','2025-04-29');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (16,3,'IT50001RTKWA5I','2025-01-21');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (17,3,'IT50066ZUBO5ZI','2025-06-04');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (18,3,'IT25-AEUI-11331511','2025-08-27');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (19,3,'IT25-AEUI-11806566','2025-09-04');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (20,5,'IT5000LKJY4E5I','2025-09-23');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (21,1,'387.0','2019-07-22');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (22,1,'19.0','2024-11-21');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (23,1,'388.0','2019-07-22');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (24,1,'64.0','2020-01-29');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (25,6,'56.0','2023-09-25');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (26,7,'5500090.0','2026-01-07');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (27,1,'69.0','2018-02-21');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (28,8,'74.0','2020-03-10');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (29,9,'1136.0','2021-02-26');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (30,9,'2185.0','2017-10-31');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (31,10,'198870.0','2023-11-24');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (32,3,'162.0','2020-09-25');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (33,3,'220.0','2021-06-17');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (34,3,'6286811.0','2020-10-29');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (35,3,'3311512.0','2021-04-23');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (36,3,'2.0','2022-09-29');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (37,3,'8713527.0','2022-09-14');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (38,3,'4.0','2022-12-19');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (39,3,'cz215','2022-12-12');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (40,3,'IT24-AEUI-6595096','2024-06-03');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (41,3,'417/FAM','2024-07-15');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (42,11,'6688.0','2018-11-13');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (43,11,'24/69/01302','2024-12-10');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (44,3,'767/FAM','2025-09-08');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (45,12,'88306.0','2018-12-31');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (46,12,'6394.0','2019-01-29');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (47,12,'7824.0','2019-11-21');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (48,12,'71277.0','2022-02-23');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (49,12,'449543678.0','2024-10-17');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (50,12,'91412.0','2021-11-30');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (51,12,'549022984.0','2025-01-16');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (52,12,'549363464.0','2025-07-06');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (53,13,'96.0','2016-03-12');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (54,12,'9282.0','2023-10-25');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (55,12,'549657331.0','2025-12-11');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (56,12,'3067.0','2023-07-20');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (57,12,'255.0','2023-05-11');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (58,14,'78.0','2024-02-22');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (59,7,'4302257.0','2026-03-02');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (60,3,'6556306/I','2026-04-30');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (61,16,'11/R','2026-09-02');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (62,1,'388.0','2019-07-21');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (63,1,'276.0','2021-06-08');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (64,12,'7649440097.0','2026-09-08');
INSERT INTO fattura (id,fornitore_id,numero,data) VALUES (65,3,'DE6398E1VAEUI','2026-09-23');
ALTER TABLE asset DISABLE TRIGGER asset_movimenti;
-- asset
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (1,'PC','Assegnato',40,'Dell','Optiplex 3050',8,1000,'Windows 10','7V33MP2','Pc-Pietro',1,1,1,1,'2018-06-01',468.95,NULL,'Wifi non originale');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (2,'Server','Estinto',NULL,NULL,'SRVAPP01',NULL,NULL,NULL,NULL,'SRVAPP01',1,2,1,2,'2018-10-31',7300.0,NULL,'Da partitario 2025/26 (reg. 03/09/26), fattura in reverse charge, protocollo 11, partita 60039/I. Verificare se sostituisce l''HP cespite 98 e in tal caso dismettere quello. Serial e cespite da rilevare — Migrazione stati: era "Dismesso" senza destinazione: stabilire se venduto, ceduto o macerato');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (3,'PC','Assegnato',11,'HP','ProBook 430 G6',8,512,'Windows 10','5CD93196L3','Notebook-Dario',1,3,1,3,'2019-10-04',890.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (4,'PC','Assegnato',20,'HP','Core i5 14"',16,512,'Windows 10 Pro','5CD0228T11','Notebook-Fausto',1,4,1,4,'2020-10-29',807.5,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (5,'PC','Assegnato',39,'HP','Core i5 14"',16,512,'Windows 10 Pro','5CD0228T00','Notebook-Piero',1,4,1,4,'2020-10-29',807.5,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (6,'PC','Assegnato',1,'HP','Core i5 14"',16,512,'Windows 10 Pro',NULL,NULL,1,4,1,4,'2020-10-29',807.5,NULL,'Serial number mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (7,'PC','Assegnato',8,'HP','Core i5 14"',16,512,'Windows 10 Pro','5CD1136VC3','Notebook-Chiara',1,5,1,5,'2021-04-27',800.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (8,'PC','Assegnato',41,'HP','Core i5 14"',16,512,'Windows 10 Pro','5CD1136VBK','Notebook-Rossella',1,6,1,6,'2021-05-13',800.0,NULL,'Da verificare: nel file originale risultava in stanza server ma intestato a Rossella Cortese');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (9,'PC','Macerato',NULL,'HP','Core i5 14"',16,512,'Windows 10 Pro','5CD148DNYJ',NULL,1,7,2,7,'2022-11-24',700.82,NULL,'Sostituito dal PC Mediaworld 2026 — Migrazione stati: da "Dismesso" con destinazione "Rottamato"');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (10,'PC','Assegnato',3,'MSI','n.d.',NULL,NULL,NULL,'9S714C612055ZN1000261','Notebook-Andrea',1,8,3,8,'2023-05-16',818.85,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (11,'PC','Assegnato',15,'HP','Core i5 14"',16,1000,'Windows 11','5CD3212RMG','Notebook-ElenaM',1,9,1,9,'2023-08-31',1530.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (12,'PC','Assegnato',33,'HP','Core i5 14"',16,1000,'Windows 11','5CD32349DP','NB-Lucia',1,10,1,10,'2023-09-07',1530.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (13,'PC','Assegnato',34,'HP','Core i7 17"',16,1000,'Windows 11','5CG250068D','NB-Ludovica',1,11,1,11,'2023-09-19',1790.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (14,'PC','Da verificare',18,'HP','Core i7 15"',16,NULL,'Windows 11','CND23704WD','NB-Elisa',1,12,4,12,'2023-09-23',676.97,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (15,'PC','Assegnato',28,'HP','AMD Ryzen 5 5500U',8,256,'Windows 11','CND31950TC','Notebook-Guido',1,13,3,13,'2024-06-03',327.79,NULL,'Evidenziato in rosso nel file originale: da verificare');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (16,'PC','Assegnato',23,'Lenovo','Core i7 15"',16,1000,'Windows 11 Pro','PF51F04H','PC-FRANCESCO',1,14,3,14,'2024-08-13',731.18,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (17,'PC','Assegnato',36,'HP','Core i7 15"',32,1000,'Windows 11','5CD5024TPY','NB-Martina',1,15,1,15,'2025-04-29',940.0,NULL,'Da Fatturare a Le parole');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (18,'PC','Assegnato',35,'HP','Core i5 14"',16,1000,'Windows 11',NULL,'Notebook-Maria',1,16,3,16,'2025-01-21',259.02,NULL,'Serial number mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (19,'PC','Venduto',NULL,'HP','Core i5 15,6"',16,512,'Windows 11 Pro',NULL,'Notebook-Alessia',1,17,3,17,'2025-06-04',271.76,'2026-09-28','Serial number mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (20,'PC','Assegnato',12,'HP','Intel Core Ultra 5-125H',16,1000,'Windows 11','5CD449BJPS','PCDAVIDE',1,18,3,18,'2025-08-27',759.42,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (21,'PC','Assegnato',42,'HP','Intel Core i5-13345U',16,512,'Windows 11',NULL,'PC-SABINA2',1,19,3,19,'2025-09-04',393.43,NULL,'Serial number mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (22,'PC','Assegnato',16,'HP','Intel Core i7-1355U',32,1000,'Windows 11','5CD4449JMB','NB-ELENAP',1,20,5,20,'2025-09-23',842.64,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (23,'PC','Macerato',NULL,'HP','280 MT',8,500,'Windows 10','K1N0CV064457038','PC-Elena',1,21,1,21,'2019-07-22',485.0,'2026-09-14','Wifi non originale — Migrazione stati: da "In magazzino / stanza server", dedotto dalla tipologia PC');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (24,'Server','In esercizio',NULL,NULL,'Server nuovo',NULL,NULL,NULL,NULL,'TERRE-SRVDC',1,22,1,22,'2024-11-21',8028.0,NULL,'Migrazione stati: da "In magazzino / stanza server", dedotto dalla tipologia Server');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (25,'PC','Assegnato',14,'HP','ProBook 430 G6',8,512,'Windows 10','5CD9213334','Notebook-Elena',2,23,1,23,'2019-07-22',890.0,NULL,'Cespite mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (26,'PC','Assegnato',21,'HP','ProBook 440 G6',8,512,'Windows 10','5CD9390LOP','notebook-francesca',2,24,1,24,'2020-01-29',890.0,NULL,'Cespite mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (27,'PC','Assegnato',10,'HP','Core i5 14"',16,512,'Windows 10 Pro','5CD0228SZP','Notebook-Corinne',2,25,6,25,'2023-09-25',565.25,NULL,'Revisione: "riga da cancellare", sarebbe il cespite 80 passato a Le parole come 28');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (28,'PC','Assegnato',42,'HP','Core i5 14"',16,512,'Windows 10 Pro','5CD148DNZV','Notebook-Sabina',2,26,2,7,'2022-11-24',700.82,NULL,'Cespite corretto da 89 a 29 nella revisione leparole');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (29,'PC','Assegnato',45,'HP','14-EW1008 (Core Ultra 7 155H) 14 pollici',32,NULL,'Windows 11','00342-21338-71588-AAOEM','Notebook-Stefania',1,27,7,26,'2026-01-07',881.1,NULL,'Dati completati dal partitario Macchine elettroniche ufficio 2025/26 (reg. 08/01/26). N. cespite da assegnare');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (30,'Tablet','Assegnato',33,'Apple','iPad',NULL,NULL,NULL,NULL,'Ipad',1,28,1,27,'2018-02-21',508.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (31,'Mac','Disponibile',NULL,'Apple','iMac 21,5"',16,256,'macOS','DGKNQ0EZF8J8',NULL,1,29,8,28,'2020-03-10',775.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (32,'Mac','Assegnato',13,'Apple','MacBook Pro 13"',8,256,'macOS','C02CKMU7P3XY',NULL,1,30,9,29,'2021-02-26',1149.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (33,'Mac','Assegnato',38,'Apple','MacBook Air',8,NULL,'macOS','C02V63QVHH21',NULL,1,31,9,30,'2017-10-31',1277.05,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (34,'Mac','Assegnato',38,'Apple','MacBook Air',8,NULL,'macOS',NULL,NULL,1,32,10,31,'2023-11-24',570.48,NULL,'Serial number mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (35,'Mac','Assegnato',4,'Apple','MacBook Pro 16"',16,512,'macOS','C02CX2H6MD6M',NULL,1,33,3,32,'2020-09-25',1824.22,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (36,'Mac','Assegnato',5,'Apple','MacBook Pro 16"',16,512,'macOS','C02F90VZMD6M',NULL,1,34,3,33,'2021-06-17',2104.95,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (37,'Mac','Assegnato',43,'Apple','MacBook Pro 16"',16,512,'macOS','C07XM4TRJYVW',NULL,1,35,3,34,'2020-10-29',1843.34,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (38,'Mac','Assegnato',32,'Apple','MacBook Pro 13"',8,256,'macOS','FVFFF1XNQ05D',NULL,1,36,3,35,'2021-04-23',1105.74,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (39,'Mac','Assegnato',25,'Apple','MacBook Pro 13"',8,256,'macOS','Q5NH69WD6G',NULL,1,37,3,36,'2022-09-29',1190.98,NULL,'Stesso cespite 88 di Eleonora Armaroli');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (40,'Mac','Assegnato',44,'Apple','MacBook Pro 13"',8,256,'macOS','M17J97G9TK',NULL,1,38,3,37,'2022-09-14',1216.39,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (41,'Mac','Assegnato',26,'Apple','MacBook Pro 13"',8,256,'macOS','R56K94WCMC',NULL,1,39,3,38,'2022-12-19',1146.72,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (42,'Mac','Assegnato',17,'Apple','MacBook Pro 13"',8,256,'macOS','WJKFKWQHG4',NULL,1,37,3,36,'2022-09-29',1190.98,NULL,'Stesso cespite 88 di Giulia Genovesi');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (43,'Mac','Assegnato',29,'Apple','MacBook Air 13"',8,256,'macOS','C02QP9BXFVH5',NULL,1,40,3,39,'2022-12-12',1151.71,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (44,'Mac','Assegnato',9,'Apple','MacBook Air 13"',8,256,'macOS','D4RJ4VK364',NULL,1,41,3,40,'2024-06-03',802.46,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (45,'Mac','Assegnato',27,'Apple','MacBook Air 13"',8,256,'macOS',NULL,NULL,1,42,3,41,'2024-07-15',1073.77,NULL,'Serial number mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (46,'Mac','Disponibile',NULL,'Apple','Mac mini',16,NULL,'macOS',NULL,NULL,1,43,11,42,'2018-11-13',753.28,NULL,'Da verificare: nel file originale risultava in stanza server ma intestato a Mattia Gadda — Migrazione stati: da "In magazzino / stanza server", dedotto dalla tipologia Mac');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (47,'Mac','Assegnato',6,'Apple','iMac Retina 4,5K 24"',8,256,'macOS',NULL,NULL,1,44,11,43,'2024-12-10',851.64,NULL,'Serial number mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (48,'Mac','Assegnato',22,'Apple','iMac Retina 4,5K 24"',16,256,'macOS',NULL,NULL,1,45,3,44,'2025-09-08',1221.31,NULL,'Serial number mancante');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (49,'Telefono','Disponibile',NULL,'Huawei','ANE-LX1',NULL,NULL,'Android 9',NULL,'Andrea''s ANE-LX1',1,NULL,12,45,'2018-12-31',137.25,NULL,'Importo = quota a costo (9,15 x 15)');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (50,'Telefono','Assegnato',8,'Xiaomi','Redmi Note 6 Pro',NULL,NULL,'Android 9',NULL,'HUAWEI MATE 20 LITE',1,NULL,12,46,'2019-01-29',270.0,NULL,'Device name e modello non coincidono nel file originale');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (51,'Telefono','Assegnato',18,'Huawei','ANE-LX1',NULL,NULL,'Android 9',NULL,'Elisa''s ANE-LX1',1,NULL,12,45,'2018-12-31',137.25,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (52,'Telefono','Assegnato',23,'Samsung','SM-A405FN',NULL,NULL,'Android 10',NULL,'Francesco''s SM-A405FN',1,NULL,12,47,'2019-11-21',165.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (53,'Telefono','Assegnato',41,'Huawei','ANE-LX1',NULL,NULL,'Android 9',NULL,'Rossella''s ANE-LX1',1,NULL,12,45,'2018-12-31',137.25,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (54,'Telefono','Assegnato',38,'Huawei','CAN-L01',NULL,NULL,'Android',NULL,'Miriam''s HUAWEI CAN-L01',1,NULL,12,46,'2019-01-29',225.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (55,'Telefono','Assegnato',31,'Huawei','ANE-LX1',NULL,NULL,'Android 9',NULL,'Piero''s ANE-LX1',1,NULL,NULL,NULL,NULL,NULL,NULL,'Riga senza stato nel file originale: verificare se ancora in uso');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (56,'Telefono','Assegnato',39,'Samsung','SM-A146P',NULL,NULL,'Android 13',NULL,'SM-A146P di Piero',1,46,12,48,'2022-02-23',333.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (57,'Telefono','Assegnato',45,'Samsung','SM-A405FN',NULL,NULL,'Android 9',NULL,'Stefania''s SM-A405FN',1,47,12,49,'2024-10-17',499.5,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (58,'Telefono','Non aziendale',32,'Google','Pixel',NULL,NULL,'Android',NULL,'google pixel',1,NULL,NULL,NULL,NULL,NULL,NULL,'Dispositivo di proprieta'' personale, solo SIM aziendale');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (59,'Telefono','Assegnato',34,'Xiaomi','11 Lite',NULL,NULL,'Android',NULL,'xiaomi 11 lite',1,48,12,50,'2021-11-30',300.0,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (60,'Telefono','Assegnato',15,'Apple','iPhone',NULL,NULL,'iOS',NULL,'iphone',1,49,12,51,'2025-01-16',849.15,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (61,'Telefono','Assegnato',12,'Honor','Honor',NULL,NULL,'Android',NULL,'honor',1,50,12,52,'2025-07-06',135.0,NULL,'Riga senza stato nel file originale');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (62,'Telefono','Da verificare',33,'Samsung','SM-A405FN',NULL,NULL,'Android 9',NULL,'Lucia''s SM-A405FN',2,51,13,53,'2016-03-12',114.67,NULL,'Importo = quota a costo — Revisione: telefono ex Nicoletta, gia'' dismesso. Da cancellare o dismettere');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (63,'Telefono','Assegnato',42,'Motorola','moto g54 5g',NULL,NULL,'Android 15',NULL,NULL,2,NULL,12,NULL,'2023-11-27',0.0,NULL,'Cercare eventuale fattura');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (64,'Telefono','Assegnato',14,'Samsung','Galaxy a13',NULL,NULL,'Android 13',NULL,NULL,2,NULL,12,NULL,'2023-02-27',0.0,NULL,'Cespite 2 duplicato con il telefono di Sabina Eleonori — Revisione: Elena usa ancora un Huawei del 2019? Il cespite risulta gia'' dismesso');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (65,'Telefono','Assegnato',10,'Samsung','SM-A415F',NULL,NULL,'Android 10',NULL,'Corinne''s SM-A415F',1,NULL,12,54,'2023-10-25',154.0,NULL,'A costo di Cart''armata — Revisione: "non e'' di Le parole, va sotto Cart''armata"');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (66,'Telefono','Assegnato',21,'Apple','iPhone 15 128GB Black',NULL,NULL,'iOS',NULL,'IPHONE',2,52,12,55,'2025-12-11',632.7,NULL,'Dati completati dalla revisione leparole');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (67,'Telefono','Assegnato',36,'Apple','iPhone',NULL,NULL,'iOS',NULL,'IPHONE',2,53,12,56,'2023-07-20',799.2,NULL,NULL);
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (68,'Telefono','Da verificare',NULL,'Apple','iPhone',NULL,NULL,'iOS',NULL,'IPHONE',2,54,12,57,'2023-05-11',799.2,NULL,'Venduto, fattura 12 del 10/12/2025 (revisione leparole) — Migrazione stati: era "Dismesso" con destinazione "Sostituito": stabilire se venduto, ceduto o macerato');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (69,'Altro','In esercizio',NULL,NULL,'Centralino telefonico',NULL,NULL,NULL,NULL,'NUOVO CENTRALINO',1,55,14,58,'2024-02-22',700.0,NULL,'Nel file originale l''utente era ''?????'' — Migrazione stati: da "In magazzino / stanza server", dedotto dalla tipologia Altro');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (70,'Altro','In esercizio',NULL,NULL,'Centralino telefonico Setis',NULL,NULL,NULL,NULL,NULL,1,56,15,NULL,NULL,4900.0,NULL,'Voce senza data/fattura nel file originale — Migrazione stati: da "In magazzino / stanza server", dedotto dalla tipologia Altro');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (71,'Altro','In esercizio',NULL,NULL,'Sdoppiatore telefonico',NULL,NULL,NULL,NULL,NULL,1,57,NULL,NULL,NULL,31.12,NULL,'Da riepilogo del foglio originale — Migrazione stati: da "In magazzino / stanza server", dedotto dalla tipologia Altro');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (72,'Altro','In esercizio',NULL,NULL,'Switch e installazione',NULL,NULL,NULL,NULL,NULL,1,58,NULL,NULL,NULL,803.0,NULL,'Da riepilogo del foglio originale — Migrazione stati: da "In magazzino / stanza server", dedotto dalla tipologia Altro');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (73,'Telefono','Assegnato',3,'Samsung','Galaxy S25 Ultra',NULL,135,'Android',NULL,NULL,1,59,7,59,'2026-03-02',1494.61,NULL,'Da partitario 2025/26 (reg. 03/03/26). Importo comprensivo di cover, assicurazione e caricabatterie. Verificare se sostituisce l''ANE-LX1 e in tal caso dismettere quello. Serial e cespite da rilevare');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (74,'Tablet','Assegnato',33,'Lenovo','Tab 10.1" FHD, Helio G85, 4/128 GB, WiFi 6',4,128,'Android 14',NULL,NULL,1,60,3,60,'2026-04-30',138.52,NULL,'Da partitario 2025/26 (reg. 01/05/26). Clear Case Polar Blue incluso. Assegnatario, serial e cespite da rilevare');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (75,'PC','Assegnato',18,'Acer','Notebook Intel Core Ultra 7 155U Meteor Lake',16,512,'Windows 11',NULL,'Notebook-Elisa',1,61,16,61,'2026-09-02',848.36,NULL,'Da partitario 2025/26 (reg. 03/09/26), fattura in reverse charge, protocollo 11, partita 60039/I. Verificare se sostituisce l''HP cespite 98 e in tal caso dismettere quello. Serial e cespite da rilevare');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (76,'PC','Macerato',NULL,'HP','Microtower',NULL,NULL,NULL,NULL,NULL,2,62,1,62,'2019-07-21',485.0,'2026-09-14','Da revisione foglio leparole — Microtower di Corinne. Annotato "esiste ancora": confermare stato e assegnatario — Migrazione stati: era "Dismesso" senza destinazione: stabilire se venduto, ceduto o macerato');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (78,'PC','Macerato',NULL,'HP','NOTEBOOK N6.6 i5-1035G1 14"',16,512,'Windows 10 Professional','5CD1136V0W','Notebook-Martina',2,63,1,63,'2021-06-08',800.0,'2026-09-14','Da import fattura EFFESISTEMI srl a socio unico n. 276 (PDF)');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (79,'Telefono','Assegnato',11,'Apple','iPhone 17 256GB Mist Blue',NULL,NULL,NULL,NULL,NULL,2,NULL,12,64,'2026-09-08',780.0,NULL,'Da import fattura Wind Tre S.p.A. con Socio Unico n. 7649440097 (PDF) — IMEI/rateizzazione 354189504942999 · DDT 60458653 del 09/09/2026');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (80,'Telefono','Assegnato',7,'Google','Google Pixel 10 Pro XL',NULL,512,NULL,NULL,NULL,1,64,3,65,'2026-09-23',1036.25,NULL,'Da import fattura CART''ARMATA EDIZIONI SRL n. ? (PDF)');
INSERT INTO asset (id,tipologia,stato,persona_id,marca,modello,ram_gb,storage_gb,sistema_operativo,serial,hostname,azienda_id,cespite_id,fornitore_id,fattura_id,data_acquisto,importo,data_dismissione,note) VALUES (81,'Altro','In esercizio',NULL,'Huawei','IdeaHub S3 65 HUAWEI',NULL,NULL,NULL,NULL,NULL,1,65,1,NULL,'2026-09-29',5900.0,NULL,NULL);
ALTER TABLE asset ENABLE TRIGGER asset_movimenti;
-- sim
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (1,'3929462811','Attiva',3,'Wind','MYSHARE UNLIMITED',15.0,1,73,'15 GB',true,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (2,'3459011837','Attiva',8,'Wind','MYSHARE UNLIMITED',15.0,1,50,'15 GB',true,NULL,'Saponetta: Si (2)');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (3,'3335360573','Attiva',18,'Wind','MYSHARE UNLIMITED',15.0,1,51,'15 GB',true,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (4,'3341665241','Attiva',23,'Wind','SUPER Unlimited',17.99,1,52,'Illimitati',false,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (5,'3929708044','Attiva',41,'Wind','MYSHARE UNLIMITED',15.0,1,53,'15 GB',true,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (6,'3663848147','Attiva',38,'Wind','SUPER Unlimited',17.99,1,54,'Illimitati',true,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (7,'3495214692','Attiva',39,'Wind','MYSHARE UNLIMITED',15.0,1,56,'15 GB',NULL,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (8,'3662811886','Attiva',45,'Wind','SUPER Unlimited',17.99,1,57,'Illimitati',true,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (9,'3485406139','Attiva',32,'Wind','SUPER Unlimited',17.99,1,58,'Illimitati',NULL,NULL,'Telefono di proprieta'' personale');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (10,'3382542144','Attiva',34,'Wind','SUPER Unlimited',17.99,1,59,'Illimitati',NULL,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (11,'3275338276','Attiva',15,'Wind','SUPER Unlimited',17.99,1,60,NULL,NULL,NULL,'Nel file originale: 327 533 8276');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (12,'3899581380','Attiva',12,'Wind',NULL,NULL,NULL,61,NULL,NULL,NULL,'Numero non presente nel file originale (xxxxxx)');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (13,'3938488001','Attiva',33,'Wind','SUPER Unlimited',17.99,2,62,'Illimitati',true,NULL,'Saponetta: Si in ufficio');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (14,'3333939193','Attiva',42,'Wind','SUPER Unlimited',17.99,2,63,'Illimitati',true,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (15,'3459011715','Attiva',14,'Wind','SUPER Unlimited',17.99,2,64,'Illimitati',true,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (16,'3332022960','Attiva',10,'Wind','SUPER Unlimited',17.99,2,65,'Illimitati',false,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (17,'3311316484','Attiva',21,'Wind','SUPER Unlimited',17.99,2,66,NULL,NULL,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (18,'3275229288','Attiva',36,'Wind','SUPER Unlimited',17.99,2,67,NULL,NULL,NULL,NULL);
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (19,'3202709938','Attiva',NULL,'Wind','SUPER Giga Unlimited',NULL,1,NULL,NULL,NULL,NULL,'SIM dati - Grande Fabbrica. Row Id 1-65RGEKX8 / PHX70101 / postpaid');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (20,'3804315262','Cessata',NULL,'Wind','ONLY GIGA',NULL,1,NULL,NULL,NULL,NULL,'SIM dati prepagata. Row Id 1-5R6BCBU3 / PHX00151');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (21,'3898949400','Cessata',NULL,'Wind','ONLY GIGA',NULL,1,NULL,NULL,NULL,NULL,'SIM dati prepagata. Row Id 1-5R6G0H9T / PHX00151');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (22,'3290624609','Cessata',NULL,'Wind','ONLY GIGA',NULL,1,NULL,NULL,NULL,NULL,'SIM dati prepagata. Row Id 1-5R6E4NNZ / PHX00151');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (23,'3291538775','Cessata',NULL,'Wind','ONLY GIGA',NULL,1,NULL,NULL,NULL,NULL,'SIM dati prepagata. Row Id 1-5R6EELSG / PHX00151');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (24,'3891525853','Cessata',NULL,'Wind','ONLY GIGA',NULL,1,NULL,NULL,NULL,NULL,'SIM dati prepagata. Row Id 1-5R6ENS39 / PHX00151');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (25,'3297694352','Cessata',NULL,'Wind','ONLY GIGA',NULL,1,NULL,NULL,NULL,NULL,'SIM dati prepagata. Row Id 1-5R6FWP7X / PHX00151');
INSERT INTO sim (id,numero,stato,persona_id,operatore,piano,costo_mensile,azienda_id,asset_id,giga_telefono,saponetta,giga_saponetta,note) VALUES (26,'3208561209','Da verificare',NULL,'Wind','SUPER Giga Unlimited',NULL,1,NULL,NULL,NULL,NULL,'Nel file originale: ''sara'' quella di miriam?''');
-- movimenti
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-08','Consegna',74,NULL,33,NULL,NULL,'(automatico) assegnatario: - -> Lucia Chierici',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-08','Riconsegna',31,2,NULL,NULL,NULL,'(automatico) assegnatario: Alessia Boccardo -> -',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-08','Rientro in magazzino',49,3,NULL,'Assegnato',NULL,'(automatico) stato: Assegnato -> In magazzino / stanza server',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-08','Riconsegna',49,3,NULL,NULL,NULL,'(automatico) assegnatario: Andrea Raspanti -> -',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-08','Riassegnazione',30,3,33,NULL,NULL,'(automatico) assegnatario: Andrea Raspanti -> Lucia Chierici',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-08','Riconsegna',46,37,NULL,NULL,NULL,'(automatico) assegnatario: Mattia Gadda -> -',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-08','Rientro in magazzino',19,NULL,NULL,'Da verificare',NULL,'(automatico) stato: Da verificare -> In magazzino / stanza server',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-08','Riconsegna',19,2,NULL,NULL,NULL,'(automatico) assegnatario: Alessia Boccardo -> -',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-09','Cambio stato',8,41,NULL,NULL,'Assegnato','(automatico) stato: In magazzino / stanza server -> Assegnato',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-09','Riconsegna',68,21,NULL,NULL,NULL,'(automatico) assegnatario: Francesca Clarichetti -> -',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-09','Riconsegna',9,45,NULL,NULL,NULL,'(automatico) assegnatario: Stefania Falbo -> -',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Rientro in magazzino',18,35,NULL,'Da verificare','Disponibile','(automatico) stato: Da verificare -> Disponibile',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Riconsegna',18,35,NULL,NULL,NULL,'(automatico) assegnatario: Maria Santagata -> -',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Cambio stato',68,11,NULL,'Da verificare','Assegnato','(automatico) stato: Da verificare -> Assegnato',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Consegna',68,NULL,11,NULL,NULL,'(automatico) assegnatario ora: Dario Paladini — valore precedente non disponibile (modifica multipla)',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Messa in esercizio',2,NULL,NULL,'Da verificare','In esercizio','(automatico) stato: Da verificare -> In esercizio',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Messa fuori uso',76,NULL,NULL,'Da verificare','Estinto','(automatico) stato: Da verificare -> Estinto',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Cambio stato',68,NULL,NULL,'Assegnato','Da verificare','(automatico) stato: Assegnato -> Da verificare',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Riconsegna',68,11,NULL,NULL,NULL,'(automatico) assegnatario: Dario Paladini -> -',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Consegna',79,NULL,11,NULL,NULL,'(automatico) assegnatario ora: Dario Paladini — valore precedente non disponibile (modifica multipla)',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-11','Cambio stato',79,11,NULL,'Da verificare','Assegnato','(automatico) stato: Da verificare -> Assegnato',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-14','Macero',76,NULL,NULL,'Estinto','Macerato','(automatico) stato: Estinto -> Macerato',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-14','Macero',23,NULL,NULL,'Disponibile','Macerato','(automatico) stato: Disponibile -> Macerato',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-14','Cambio stato',22,16,NULL,'Assegnato','Da verificare','(automatico) stato: Assegnato -> Da verificare',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-14','Riassegnazione',78,36,16,NULL,NULL,'(automatico) assegnatario: Martina Malachin -> Elena Parasiliti',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-14','Macero',78,NULL,NULL,'Assegnato','Macerato','(automatico) stato: Assegnato -> Macerato',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-14','Riconsegna',78,16,NULL,NULL,NULL,'(automatico) assegnatario: Elena Parasiliti -> -',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-14','Cambio stato',22,16,NULL,'Da verificare','Assegnato','(automatico) stato: Da verificare -> Assegnato',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-16','Messa fuori uso',2,NULL,NULL,'In esercizio','Estinto','(automatico) stato: In esercizio -> Estinto',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-22','Cambio stato',18,NULL,NULL,'Disponibile','Assegnato','(automatico) stato: Disponibile -> Assegnato',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-24','Consegna',80,NULL,7,NULL,NULL,'(automatico) assegnatario ora: Chiara Cuzzola — valore precedente non disponibile (modifica multipla)',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-24','Cambio stato',80,7,NULL,'Da verificare','Assegnato','(automatico) stato: Da verificare -> Assegnato',true);
INSERT INTO movimento (data,tipo,asset_id,da_persona_id,a_persona_id,stato_prima,stato_dopo,note,automatico) VALUES ('2026-09-28','Vendita',19,NULL,NULL,'Disponibile','Venduto','(automatico) stato: Disponibile -> Venduto',true);
-- antivirus
INSERT INTO antivirus_import (id,importato,file_nome) VALUES (1,'2026-09-16 09:53:00','importazione da foglio');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'ACER','Protetto','ACER','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:53:00','10.0.0.38','E8:BF:E1:2B:D4:22');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'Lorena','Protetto','endim','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:44:00','192.168.1.3','E0:2E:0B:DE:07:41');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NB-ELENAP','Protetto','Admin','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:41:00','192.168.0.148','28:2E:89:9D:DE:11');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NB-LUCIA','Protetto','luciachierici','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:52:00','10.0.0.87','40:1A:58:3F:0F:11');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NB-LUDOVICA','Protetto','Ludovica','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:46:00','10.0.0.74','30:89:4A:C9:39:66');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NB-MARTINA','Protetto','Martina','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:40:00','192.168.1.54','48:EA:62:95:E8:D3');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-ALESSI','Non rilevato di recente','Alessia Boccardo','Windows 11.0 (Build 26200) 64bit','2026-05-29 14:51:00','10.0.0.86','30:24:A9:AB:33:4F');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-ANDREA','Protetto','Andrea Raspanti','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:40:00','172.19.192.1','00:FF:E7:4A:E7:A0');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-CHIARA','Protetto','chiara','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:50:00','10.0.0.63','A4:6B:B6:D3:75:D3');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-CORINN','Protetto','Corinne','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:48:00','10.0.0.62','B0:5C:DA:39:C7:29');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-DARIO','Protetto','Dario Paladini','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:47:00','192.168.1.23','F8:B4:6A:A7:6D:85');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-ELENA','Protetto','Elena Acerbi','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:48:00','192.168.1.162','C4:65:16:BE:B6:7E');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-ELENAM','Protetto','Elena Mancianti','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:34:00','10.0.0.81','E0:73:E7:D3:62:E8');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-FAUSTO','Protetto','Fausto Trucillo','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:42:00','10.0.0.94','B0:5C:DA:3B:BB:91');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-FRANCESCA','Protetto','Francesca','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:39:00','192.168.1.177','F8:B4:6A:BB:CB:06');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-GUIDO','Protetto','Guido Panduro','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:38:00','10.0.0.45','E0:73:E7:EF:C4:ED');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-MARIA','Protetto','Maria Santagata','Windows 11.0 (Build 22631) 64bit','2026-09-16 09:44:00','10154178218.0','7C:2A:31:CD:CA:70');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-PIERO','Protetto','Piero Magri','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:42:00','10.0.0.128','B0:5C:DA:39:C7:1A');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-ROSSEL','Protetto','Rossella Cortese','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:40:00','10.0.0.56','A4:6B:B6:D3:73:80');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-SABINA','Protetto',NULL,'Windows 11.0 (Build 26200) 64bit','2026-09-16 04:53:00','192.168.1.9','AC:74:B1:AE:60:36');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'NOTEBOOK-STEFAN','Protetto','StefaniaFalbo','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:36:00','192.168.0.48','68:C6:AC:85:25:36');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'PCDAVIDE','Protetto','david','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:45:00','192.168.0.171','FC:19:28:61:76:DD');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'PC-FRANCESCO','Protetto','LENOVO','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:45:00','192.168.1.25','C0:35:32:60:7C:44');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'PC-PIETRO','Non rilevato di recente','Pietro Scidurlo','Windows 10.0 (Build 19045) 64bit','2026-06-24 10:48:00','10.0.0.182','D8:9E:F3:4B:F7:D0');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'PC-SABINA2','Protetto','Sabina Eleonori','Windows 11.0 (Build 26200) 64bit','2026-09-16 09:47:00','10.0.0.70','38:8D:3D:13:3C:B7');
INSERT INTO antivirus_dispositivo (import_id,dispositivo,stato,utente,sistema_operativo,ultimo_rilevato,ip_locale,mac) VALUES (1,'TERRE-SRVDC','Protetto','luciachierici','Windows Server 2022 (Build 20348) 64bit','2026-09-16 09:39:00','10.0.0.10','5C:ED:8C:B0:D0:7E');
SELECT setval(pg_get_serial_sequence('persona','id'), (SELECT coalesce(max(id),1) FROM persona));
SELECT setval(pg_get_serial_sequence('fornitore','id'), (SELECT coalesce(max(id),1) FROM fornitore));
SELECT setval(pg_get_serial_sequence('cespite','id'), (SELECT coalesce(max(id),1) FROM cespite));
SELECT setval(pg_get_serial_sequence('fattura','id'), (SELECT coalesce(max(id),1) FROM fattura));
SELECT setval(pg_get_serial_sequence('asset','id'), (SELECT coalesce(max(id),1) FROM asset));
SELECT setval(pg_get_serial_sequence('sim','id'), (SELECT coalesce(max(id),1) FROM sim));
SELECT setval(pg_get_serial_sequence('movimento','id'), (SELECT coalesce(max(id),1) FROM movimento));
SELECT setval(pg_get_serial_sequence('antivirus_import','id'), (SELECT coalesce(max(id),1) FROM antivirus_import));
COMMIT;
