-- Inventario IT — Cart'armata edizioni / Le parole che servono
-- Schema PostgreSQL (bozza 1). Sostituisce il foglio Inventario_IT_2026.
-- Tabelle di anagrafica -> asset -> movimenti; Riepilogo, Dashboard, viste ▸
-- e Controllo Antivirus sono VIEW in fondo al file.

BEGIN;

-- ---------- Anagrafiche ----------
CREATE TABLE azienda (
  id    smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome  text NOT NULL UNIQUE
);

CREATE TABLE fornitore (
  id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome  text NOT NULL UNIQUE          -- una sola grafia: "Effesistemi", non "EFFESISTEMI srl a socio unico"
);

CREATE TABLE tipologia (
  nome  text PRIMARY KEY              -- PC, Mac, Tablet, Telefono, Server, Monitor, Stampante, Rete, Altro
);

-- Gli stati portano con sé le regole che prima stavano nello script
CREATE TABLE stato_asset (
  nome        text PRIMARY KEY,
  fuori       boolean NOT NULL,       -- true = "non ce l'abbiamo più": sparisce da viste e conteggi
  in_importo  boolean NOT NULL,       -- true = entra nell'importo del Riepilogo (Assegnato+In esercizio+Disponibile+Estinto)
  movimento   text NOT NULL,          -- nome del movimento registrato quando si entra in questo stato
  ordine      smallint NOT NULL
);

CREATE TABLE persona (
  id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome           text NOT NULL,
  cognome        text NOT NULL,
  email          text UNIQUE,
  azienda_id     smallint REFERENCES azienda,
  reparto        text,
  stato          text NOT NULL DEFAULT 'Attivo' CHECK (stato IN ('Attivo','Sospeso','Cessato')),
  stato_workspace text,               -- arriva dalla sincronizzazione Google Workspace
  data_ingresso  date,
  data_uscita    date,
  note           text,
  UNIQUE (nome, cognome)
);

-- Un cespite contabile (numero o codice alfanumerico) può coprire più asset (es. cespite 80 = 3 PC identici)
CREATE TABLE cespite (
  id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  azienda_id  smallint NOT NULL REFERENCES azienda,
  numero      text NOT NULL CHECK (numero ~ '^[A-Z0-9][A-Z0-9._/-]{0,29}$'),   -- alfanumerico, maiuscolo (es. 48, A12, 2019/07)
  note        text,
  UNIQUE (azienda_id, numero)
);

CREATE TABLE fattura (
  id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fornitore_id  int NOT NULL REFERENCES fornitore,
  numero        text NOT NULL,        -- senza spazi iniziali/finali
  data          date,
  UNIQUE (fornitore_id, numero, data), -- "255" esiste sia per Effesistemi 2023 sia per Wind 2023
  UNIQUE (id, fornitore_id)
);

-- Cespiti ante 2018: copia di sola lettura del foglio storico, per la quadratura con l'amministrazione.
-- Non collegata ad azienda/asset: il foglio non indica l'azienda e i numeri si sovrappongono (Cart'armata e Le parole).
CREATE TABLE cespite_storico (
  id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria     text NOT NULL,            -- computer, mac, tablet, eliminati
  numero        int NOT NULL UNIQUE,
  data          date,
  fornitore     text,                     -- come scritto nel foglio, senza normalizzazione
  descrizione   text,
  col_h         numeric(10,2),            -- colonna "Col H" del foglio (significato non documentato)
  da_trovare_eliminare numeric(10,2),
  da_abbinare   numeric(10,2),
  note          text
);

-- ---------- Asset ----------
CREATE TABLE asset (
  id               int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codice           text GENERATED ALWAYS AS ('AST-' || lpad(id::text, 3, '0')) STORED UNIQUE,
  tipologia        text NOT NULL REFERENCES tipologia,
  stato            text NOT NULL REFERENCES stato_asset,
  persona_id       int REFERENCES persona,         -- "Assegnato a"
  marca            text,
  modello          text,
  ram_gb           smallint CHECK (ram_gb BETWEEN 1 AND 1024),
  storage_gb       int CHECK (storage_gb > 0),
  sistema_operativo text,
  serial           text,
  hostname         text,                            -- "Nome dispositivo"
  azienda_id       smallint NOT NULL REFERENCES azienda,
  cespite_id       int REFERENCES cespite,
  fornitore_id     int REFERENCES fornitore,        -- anche senza fattura (es. AST-081)
  fattura_id       int,
  data_acquisto    date,
  importo          numeric(10,2) CHECK (importo >= 0),
  data_dismissione date,
  note             text,
  FOREIGN KEY (fattura_id, fornitore_id) REFERENCES fattura (id, fornitore_id), -- fornitore dell'asset = fornitore della fattura
  -- Regola: assegnatario se e solo se Assegnato (o Da verificare/Non aziendale, dove può esserci).
  CONSTRAINT assegnatario_coerente CHECK (
    (stato = 'Assegnato' AND persona_id IS NOT NULL)
    OR (stato IN ('In esercizio','Disponibile','Estinto','Venduto','Ceduto','Macerato','Smarrito/Rubato') AND persona_id IS NULL)
    OR stato IN ('Da verificare','Non aziendale')
  )
);
CREATE UNIQUE INDEX asset_serial_uq ON asset (upper(serial)) WHERE serial IS NOT NULL AND serial <> '';
CREATE INDEX asset_persona_ix  ON asset (persona_id);
CREATE INDEX asset_stato_ix    ON asset (stato);
CREATE INDEX asset_hostname_ix ON asset (upper(hostname));

CREATE TABLE sim (
  id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codice       text GENERATED ALWAYS AS ('SIM-' || lpad(id::text, 3, '0')) STORED UNIQUE,
  numero       text UNIQUE,
  stato        text NOT NULL CHECK (stato IN ('Attiva','Sospesa','Cessata','Da verificare')),
  persona_id   int REFERENCES persona,
  operatore    text,
  piano        text,
  costo_mensile numeric(8,2),
  azienda_id   smallint REFERENCES azienda,
  asset_id     int REFERENCES asset,               -- telefono in cui è montata (prima: testo libero)
  giga_telefono text,
  saponetta    boolean,
  giga_saponetta text,
  note         text
);

-- ---------- Storico ----------
CREATE TABLE movimento (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data          date NOT NULL DEFAULT current_date,
  tipo          text NOT NULL,                     -- Consegna, Riconsegna, Riassegnazione, <movimento dello stato>, Cambio stato
  asset_id      int REFERENCES asset ON DELETE SET NULL, -- NULL = asset eliminato (vedi oggetto) o eliminazione di persona/SIM
  da_persona_id int REFERENCES persona,
  a_persona_id  int REFERENCES persona,
  stato_prima   text,
  stato_dopo    text,
  note          text,
  automatico    boolean NOT NULL DEFAULT true,
  oggetto       text,                              -- descrizione di ciò che è stato eliminato / dell'asset eliminato
  utente        text                               -- chi ha fatto l'operazione (email)
);
CREATE INDEX movimento_asset_ix ON movimento (asset_id, data);

-- ---------- Antivirus ----------
CREATE TABLE antivirus_import (
  id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  importato  timestamptz NOT NULL DEFAULT now(),
  file_nome  text
);
CREATE TABLE antivirus_dispositivo (
  import_id      int NOT NULL REFERENCES antivirus_import ON DELETE CASCADE,
  dispositivo    text NOT NULL,
  stato          text,                              -- Protetto, ...
  utente         text,
  sistema_operativo text,
  ultimo_rilevato timestamptz,
  ip_locale      text,
  mac            text,
  PRIMARY KEY (import_id, dispositivo)
);

-- ---------- Dati fissi ----------
INSERT INTO azienda (nome) VALUES ('Cart''armata'), ('Le parole');
INSERT INTO tipologia VALUES ('PC'),('Mac'),('Tablet'),('Telefono'),('Server'),('Monitor'),('Stampante'),('Rete'),('Altro');
INSERT INTO stato_asset (nome, fuori, in_importo, movimento, ordine) VALUES
  ('Assegnato',       false, true,  'Consegna',            1),
  ('In esercizio',    false, true,  'Messa in esercizio',  2),
  ('Disponibile',     false, true,  'Rientro in magazzino',3),
  ('Da verificare',   false, false, 'Cambio stato',        4),
  ('Non aziendale',   false, false, 'Cambio stato',        5),
  ('Estinto',         false, true,  'Messa fuori uso',     6),
  ('Venduto',         true,  false, 'Vendita',             7),
  ('Ceduto',          true,  false, 'Cessione',            8),
  ('Macerato',        true,  false, 'Macero',              9),
  ('Smarrito/Rubato', true,  false, 'Smarrimento/Furto',  10);

-- ---------- Trigger: movimenti e data dismissione automatici ----------
-- Sostituisce lo script onEdit (registraMovimento).
CREATE FUNCTION asset_registra_movimento() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_fuori_nuovo boolean;
  v_fuori_vecchio boolean;
  v_tipo text;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    SELECT fuori INTO v_fuori_nuovo   FROM stato_asset WHERE nome = NEW.stato;
    SELECT fuori INTO v_fuori_vecchio FROM stato_asset WHERE nome = OLD.stato;
    -- data dismissione: si compila entrando in uno stato di uscita, si svuota se rientra
    IF v_fuori_nuovo AND NOT v_fuori_vecchio AND NEW.data_dismissione IS NULL THEN
      NEW.data_dismissione := current_date;
    ELSIF NOT v_fuori_nuovo AND v_fuori_vecchio THEN
      NEW.data_dismissione := NULL;
    END IF;

    IF NEW.persona_id IS DISTINCT FROM OLD.persona_id THEN
      v_tipo := CASE WHEN OLD.persona_id IS NULL THEN 'Consegna'
                     WHEN NEW.persona_id IS NULL THEN 'Riconsegna'
                     ELSE 'Riassegnazione' END;
      INSERT INTO movimento (asset_id, tipo, da_persona_id, a_persona_id, stato_prima, stato_dopo)
      VALUES (NEW.id, v_tipo, OLD.persona_id, NEW.persona_id, OLD.stato, NEW.stato);
    END IF;

    IF NEW.stato IS DISTINCT FROM OLD.stato THEN
      SELECT movimento INTO v_tipo FROM stato_asset WHERE nome = NEW.stato;
      INSERT INTO movimento (asset_id, tipo, da_persona_id, a_persona_id, stato_prima, stato_dopo)
      VALUES (NEW.id, v_tipo, OLD.persona_id, NEW.persona_id, OLD.stato, NEW.stato);
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER asset_movimenti BEFORE UPDATE ON asset
  FOR EACH ROW EXECUTE FUNCTION asset_registra_movimento();

-- ---------- Viste ----------
-- Equivalente delle viste ▸ e del conteggio "asset vivi"
CREATE VIEW v_asset AS
SELECT a.id, a.codice, a.tipologia, a.stato, p.nome || ' ' || p.cognome AS assegnato_a,
       a.marca, a.modello, a.ram_gb, a.storage_gb, a.sistema_operativo, a.serial, a.hostname,
       az.nome AS azienda, c.numero AS cespite, f.nome AS fornitore, fa.numero AS n_fattura,
       a.data_acquisto, extract(year FROM a.data_acquisto)::int AS anno,
       a.importo, a.data_dismissione, a.note, s.fuori
FROM asset a
JOIN stato_asset s ON s.nome = a.stato
JOIN azienda az    ON az.id = a.azienda_id
LEFT JOIN persona p      ON p.id = a.persona_id
LEFT JOIN cespite c      ON c.id = a.cespite_id
LEFT JOIN fattura fa     ON fa.id = a.fattura_id
LEFT JOIN fornitore f    ON f.id = a.fornitore_id;

CREATE VIEW v_asset_vivi AS SELECT * FROM v_asset WHERE NOT fuori;

-- Riepilogo: una riga per azienda e tipologia, una colonna per stato, importo sui 4 stati
CREATE VIEW v_riepilogo AS
SELECT az.nome AS azienda, t.nome AS tipologia,
  count(*) FILTER (WHERE a.stato = 'Assegnato')       AS assegnato,
  count(*) FILTER (WHERE a.stato = 'In esercizio')    AS in_esercizio,
  count(*) FILTER (WHERE a.stato = 'Disponibile')     AS disponibile,
  count(*) FILTER (WHERE a.stato = 'Da verificare')   AS da_verificare,
  count(*) FILTER (WHERE a.stato = 'Non aziendale')   AS non_aziendale,
  count(*) FILTER (WHERE a.stato = 'Estinto')         AS estinto,
  count(*) FILTER (WHERE a.stato = 'Venduto')         AS venduto,
  count(*) FILTER (WHERE a.stato = 'Ceduto')          AS ceduto,
  count(*) FILTER (WHERE a.stato = 'Macerato')        AS macerato,
  count(*) FILTER (WHERE a.stato = 'Smarrito/Rubato') AS smarrito_rubato,
  count(a.id)                                         AS totale,
  coalesce(sum(a.importo) FILTER (WHERE s.in_importo), 0) AS importo
FROM azienda az
CROSS JOIN tipologia t
LEFT JOIN asset a ON a.azienda_id = az.id AND a.tipologia = t.nome
LEFT JOIN stato_asset s ON s.nome = a.stato
GROUP BY az.nome, t.nome;

CREATE VIEW v_acquisti_per_anno AS
SELECT az.nome AS azienda, extract(year FROM a.data_acquisto)::int AS anno,
       count(*) AS n_asset, sum(a.importo) AS valore
FROM asset a JOIN azienda az ON az.id = a.azienda_id
WHERE a.data_acquisto IS NOT NULL
GROUP BY 1, 2;

-- Antivirus: confronto fra PC Windows attivi e ultimo report importato.
-- Nomi Windows troncati a 15 caratteri (NetBIOS): corrispondenza esatta o sul prefisso di 15.
CREATE FUNCTION host_norm(t text) RETURNS text LANGUAGE sql IMMUTABLE AS
$$ SELECT regexp_replace(upper(coalesce(t,'')), '[^A-Z0-9-]', '', 'g') $$;

CREATE VIEW v_controllo_antivirus AS
WITH ultimo AS (SELECT id, importato FROM antivirus_import ORDER BY id DESC LIMIT 1),
rep AS (SELECT d.*, host_norm(d.dispositivo) AS h, u.importato
        FROM antivirus_dispositivo d JOIN ultimo u ON u.id = d.import_id)
SELECT a.codice, a.azienda, a.stato, a.assegnato_a, a.hostname,
       CASE WHEN r.dispositivo IS NULL THEN 'Mancante'
            WHEN r.stato = 'Protetto' AND r.ultimo_rilevato >= r.importato - interval '20 days' THEN 'OK'
            ELSE 'Da verificare' END AS antivirus,
       r.dispositivo AS dispositivo_report, r.ultimo_rilevato
FROM v_asset_vivi a
LEFT JOIN rep r
  ON host_norm(a.hostname) <> ''
 AND (r.h = host_norm(a.hostname) OR left(r.h,15) = left(host_norm(a.hostname),15))
-- Regola: ogni PC/Server Windows ATTIVO (Assegnato, In esercizio, Da verificare) deve avere un antivirus.
-- Sistema operativo vuoto = si presume Windows. Estinto/Disponibile non sono "attivi".
WHERE a.tipologia IN ('PC','Server')
  AND (a.sistema_operativo IS NULL OR a.sistema_operativo ILIKE 'Windows%')
  AND a.stato IN ('Assegnato','In esercizio','Da verificare');

COMMIT;
