-- Cespiti ante 2018: copia di sola lettura del foglio storico, per la quadratura con l'amministrazione.
-- Non collegata ad azienda/asset: il foglio non indica l'azienda e i numeri si sovrappongono (Cart'armata e Le parole).
CREATE TABLE IF NOT EXISTS cespite_storico (
  id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria     text NOT NULL,            -- computer, mac, tablet, eliminati
  numero        int NOT NULL UNIQUE,
  data          date,
  fornitore     text,                     -- come scritto nel foglio, senza normalizzazione
  descrizione   text,
  col_h         numeric(10,2),            -- colonna "Col H" del foglio (significato non documentato)
  da_trovare_eliminare numeric(10,2),
  da_abbinare   numeric(10,2),
  note          text
);
